# -*- coding: utf-8 -*-
"""Task 4: Create FastAPI service with Docker and demo UI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lKpwU3sJnHzkvdlHfpopTCKU213VWu4h

### 1. Creating the Project Directory Structure

We will create a directory structure containing our FastAPI application (`main.py`), templates, Dockerfile, docker-compose, and test suite.
"""

import os

# Create project directories
os.makedirs('app/templates', exist_ok=True)
os.makedirs('tests', exist_ok=True)
print("Project directories created successfully!")

"""### 2. FastAPI Application (`app/main.py`)

This application exposes the `/triage` endpoint, serves a simple HTML frontend for manual testing, and automatically includes generated OpenAPI docs.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app/main.py
# from fastapi import FastAPI, HTTPException
# from fastapi.responses import HTMLResponse
# from fastapi.staticfiles import StaticFiles
# from pydantic import BaseModel, Field
# import uvicorn
# 
# app = FastAPI(
#     title="Email Triage Service",
#     description="API to classify and triage incoming raw email texts.",
#     version="1.0.0"
# )
# 
# # Pydantic models for validation
# class EmailTriageRequest(BaseModel):
#     email_text: str = Field(..., description="The raw email text content to classify.")
# 
# class EmailTriageResponse(BaseModel):
#     classification: str = Field(..., description="The predicted category (e.g., Billing, Support, Spam).")
#     confidence: float = Field(..., description="Confidence score of the classification.")
#     urgency: str = Field(..., description="Urgency level: Low, Medium, High.")
# 
# # Mock classification function (Replace with your actual model/rules classifier)
# def mock_classify_email(text: str) -> dict:
#     text_lower = text.lower()
#     if "invoice" in text_lower or "billing" in text_lower or "charge" in text_lower:
#         return {"classification": "Billing", "confidence": 0.95, "urgency": "Medium"}
#     elif "urgent" in text_lower or "broken" in text_lower or "error" in text_lower:
#         return {"classification": "Technical Support", "confidence": 0.88, "urgency": "High"}
#     elif "viagra" in text_lower or "lottery" in text_lower or "won" in text_lower:
#         return {"classification": "Spam", "confidence": 0.99, "urgency": "Low"}
#     else:
#         return {"classification": "General Inquiry", "confidence": 0.70, "urgency": "Low"}
# 
# @app.post("/triage", response_model=EmailTriageResponse, summary="Triage incoming raw email text")
# def triage_email(payload: EmailTriageRequest):
#     if not payload.email_text.strip():
#         raise HTTPException(status_code=400, detail="Email text cannot be empty.")
# 
#     result = mock_classify_email(payload.email_text)
#     return result
# 
# @app.get("/", response_class=HTMLResponse, summary="HTML Demo UI")
# def serve_demo_ui():
#     try:
#         with open("app/templates/index.html", "r") as f:
#             return HTMLResponse(content=f.read(), status_code=200)
#     except FileNotFoundError:
#         raise HTTPException(status_code=500, detail="HTML template not found.")
# 
# if __name__ == "__main__":
#     uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)

"""### 3. Frontend HTML Page (`app/templates/index.html`)

A minimal and user-friendly interface to test the endpoint live by pasting raw email text.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app/templates/index.html
# <!DOCTYPE html>
# <html lang="en">
# <head>
#     <meta charset="UTF-8">
#     <meta name="viewport" content="width=device-width, initial-scale=1.0">
#     <title>Email Triage Service Demo</title>
#     <style>
#         body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; line-height: 1.6; }
#         textarea { width: 100%; height: 150px; padding: 10px; margin-bottom: 10px; font-size: 14px; }
#         button { padding: 10px 20px; font-size: 16px; background-color: #007bff; color: white; border: none; cursor: pointer; border-radius: 4px; }
#         button:hover { background-color: #0056b3; }
#         .result-box { margin-top: 20px; padding: 15px; border: 1px solid #ddd; background-color: #f9f9f9; border-radius: 4px; display: none; }
#         pre { background: #f4f4f4; padding: 10px; border-radius: 4px; overflow-x: auto; }
#     </style>
# </head>
# <body>
#     <h1>Email Triage Classifier</h1>
#     <p>Paste the raw email content below to classify its category, confidence, and urgency level.</p>
# 
#     <textarea id="emailText" placeholder="Type or paste your raw email text here..."></textarea>
#     <button onclick="classifyEmail()">Submit for Classification</button>
# 
#     <div id="resultBox" class="result-box">
#         <h3>Triage Result:</h3>
#         <pre id="jsonResponse"></pre>
#     </div>
# 
#     <script>
#         async function classifyEmail() {
#             const emailText = document.getElementById('emailText').value;
#             const resultBox = document.getElementById('resultBox');
#             const jsonResponse = document.getElementById('jsonResponse');
# 
#             if (!emailText.trim()) {
#                 alert('Please enter some text before submitting.');
#                 return;
#             }
# 
#             try {
#                 const response = await fetch('/triage', {
#                     method: 'POST',
#                     headers: {
#                         'Content-Type': 'application/json'
#                     },
#                     body: JSON.stringify({ email_text: emailText })
#                 });
# 
#                 const data = await response.json();
#                 jsonResponse.textContent = JSON.stringify(data, null, 2);
#                 resultBox.style.display = 'block';
#             } catch (error) {
#                 console.error('Error:', error);
#                 alert('Failed to connect to the classification API.');
#             }
#         }
#     </script>
# </body>
# </html>

"""### 4. Dockerization Files (`Dockerfile` & `docker-compose.yml`)

These files package the application with all necessary environments and launch configuration on port `8000`.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile Dockerfile
# FROM python:3.10-slim
# 
# WORKDIR /workspace
# 
# # Install dependencies
# COPY requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt
# 
# # Copy app files
# COPY ./app /workspace/app
# 
# EXPOSE 8000
# 
# CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

# Commented out IPython magic to ensure Python compatibility.
# %%writefile docker-compose.yml
# version: '3.8'
# 
# services:
#   triage-service:
#     build: .
#     container_name: email-triage-container
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./app:/workspace/app
#     environment:
#       - ENV=development

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# fastapi==0.110.0
# uvicorn==0.28.0
# pydantic==2.6.4
# pytest==8.0.2
# httpx==0.27.0

"""### 5. Pytest Integration Tests (`tests/test_main.py`)

Verifies that the `/triage` route correctly handles valid and invalid requests end-to-end using `FastAPI`'s `TestClient`.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile tests/test_main.py
# from fastapi.testclient import TestClient
# import sys
# import os
# 
# sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
# from app.main import app
# 
# client = TestClient(app)
# 
# def test_triage_billing():
#     response = client.post(
#         "/triage",
#         json={"email_text": "Hi, I have a question about my invoice #1234."}
#     )
#     assert response.status_code == 200
#     data = response.json()
#     assert data["classification"] == "Billing"
#     assert "confidence" in data
#     assert "urgency" in data
# 
# def test_triage_urgent():
#     response = client.post(
#         "/triage",
#         json={"email_text": "Emergency! The application is throwing an error and is broken."}
#     )
#     assert response.status_code == 200
#     data = response.json()
#     assert data["classification"] == "Technical Support"
#     assert data["urgency"] == "High"
# 
# def test_triage_empty_text():
#     response = client.post(
#         "/triage",
#         json={"email_text": ""}
#     )
#     assert response.status_code == 400

!pip install -q fastapi uvicorn pydantic pytest httpx
!pytest tests/test_main.py