# -*- coding: utf-8 -*-
"""Task 5: Deploy to free cloud, write handover package, and demo video

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Qy0Dj5dblLxs9O9SdJPrc5SVSJoUmSf

# Task 5: Handover Package & Deployment Guide

This guide contains the resources and templates required to complete **Task 5**. Below is a complete draft for your `README.md` / Handover Document, including a Mermaid architecture diagram, maintenance runbook, and a cost estimate.

---

## 1. Handover Document & README Template

```markdown
# Email Triage Assistant - Handover & Maintenance Guide

This repository contains the Dockerised FastAPI service designed to automate email triage using LLMs. Below you will find the system architecture, deployment runbook, cost analysis, and maintenance instructions.

## ⚙️ Live Deployment Details
- **Service URL**: `https://<your-service-name>.onrender.com` (or Railway/Fly.io equivalent)
- **Health-Check Endpoint**: `https://<your-service-name>.onrender.com/health` or `/triage` (GET)
- **API Documentation**: `https://<your-service-name>.onrender.com/docs`

---

## 🗺️ System Architecture

```mermaid
graph TD
    Client[Client / Email Webhook] -->|HTTPS POST /triage| API[FastAPI Web Service]
    API -->|Read Config| Env[Environment Variables / Secrets]
    API -->|Analyze Request| LLM[LLM API / Gemini/OpenAI]
    LLM -->|Return Categorization| API
    API -->|JSON Response| Client
```

---

## 🚀 Deployment Runbook

### Deploying to Render (Free Tier)
1. **Create an Account**: Sign up at [Render.com](https://render.com).
2. **New Web Service**: Click **New +** > **Web Service** and connect your GitHub repository.
3. **Configure Settings**:
   - **Runtime**: `Docker`
   - **Instance Type**: `Free`
4. **Environment Variables**: Add your API keys under the **Environment** tab:
   - `LLM_API_KEY` = `your_api_key_here`
   - `PORT` = `8000` (Render automatically routes traffic to this port)
5. **Deploy**: Click **Deploy Web Service**.

---

## 🛠️ Maintenance & Runbook

### Health Checking
Verify that the service is running correctly by querying the health endpoint:
```bash
curl -X GET https://<your-service-name>.onrender.com/health
```
Expected response: `{"status": "healthy"}`

### Troubleshooting Logs
- **Render**: Navigate to your Web Service dashboard and click on **Logs**.
- **Local Testing**: Run `docker build -t triage-service . && docker run -p 8000:8000 --env-file .env triage-service` to debug container initialization locally.

---

## 💰 Cost Estimation (< $5/month)

| Component | Provider | Tier / Configuration | Monthly Cost |
| :--- | :--- | :--- | :--- |
| **Compute Hosting** | Render / Railway | Free Tier (500 free hours/month or $5 credit) | $0.00 |
| **LLM Inference** | Google AI Studio | Gemini 2.5 Flash (Free Tier / Pay-as-you-go) | ~$1.50 (for ~10k emails) |
| **Total** | | | **~$1.50 / month** |

---

## 🏷️ Release Management
To tag the release as `v1.0.0` and push it to GitHub:
```bash
git tag -a v1.0.0 -m "Release version 1.0.0 with Dockerised FastAPI and Render deployment config."
git push origin v1.0.0
```
```
"""

# Python helper to quickly test your live API endpoints once deployed
import requests

# Replace with your deployed URL
LIVE_URL = "https://your-service-name.onrender.com"

def verify_deployment(base_url):
    endpoints = ["/", "/docs", "/health", "/triage"]
    for endpoint in endpoints:
        url = f"{base_url.rstrip('/')}{endpoint}"
        try:
            response = requests.get(url, timeout=5) if endpoint != "/triage" else requests.post(url, json={}, timeout=5)
            print(f"[{response.status_code}] Verified {url}")
        except Exception as e:
            print(f"[ERROR] Failed to reach {url}: {e}")

# Uncomment and run once your service is live!
# verify_deployment(LIVE_URL)